### ISSUE TITLE
strip_gpio_num does not accept GPIO_NUM_NC

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/idf-extra-components#145]
Hi, 

as GPIO_NUM_NC is -1, 
the Assignment ot 

`uint32_t strip_gpio_num; /*!< GPIO number that used by LED strip */`

fails. 

in some Scenarios where a Configurable IO is wanted, we might want to temporarily connect it to NC.

**Comment by suda-morris** [comment]
> in some Scenarios where a Configurable IO is wanted, we might want to temporarily connect it to NC.

So you want to update the GPIO number dynamically? If so, you may want to delete the led_strip object and then install it with the new GPIO number.

**Comment by franz-ms-muc** [comment]
No. Not dynamic. Store in NVS. Load at Boot.

**Comment by suda-morris** [comment]
> No. Not dynamic. Store in NVS. Load at Boot.

Then can we install the led_stirp driver by checking whether the GPIO number stored in the NVS is >=0?

**Comment by franz-ms-muc** [comment]
you are right. could.
