### ISSUE TITLE
led_strip: Multiple instances

### ISSUE THREAD

**Issue by chris-est** [espressif/idf-extra-components#155]
Hello,
i have two LED strips connected to an ESP32 and would like to control them independently.

Is it possible to run multiple led_strip instances at the same time? I tried setting it up but it throws errors (my guess is every instance should use a different RMT channel?).

**Comment by suda-morris** [comment]
Hi @chris-est yes, every strip will use a new RMT channel, but the led_strip library will take care of that. `led_strip_new_rmt_device` can return a new handle if it detects there're more RMT channels free to use.

Can you demonstrate on how you set up the driver on your side and what's the error message you got?
