### ISSUE TITLE
what is the different between `json` component and `json-parser` & `json-generator`? (IEC-20)

### ISSUE THREAD

**Issue by IamFive** [espressif/idf-extra-components#184]
### Answers checklist.

- [X] I have read the documentation of the component in question and the issue is not addressed there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

why espressif add `json-parser` & `json-generator` in extra when idf already has cJSON in IDF.

**Comment by igrr** [comment]
json-parser and json-generator are dependencies of https://github.com/espressif/esp-rainmaker. It is of course possible to do the same thing using cJSON, it is just a matter of convenience and preference which API to use. If cJSON works for you, you can continue using it!
