### ISSUE TITLE
ds18b20 (IEC-23)

### ISSUE THREAD

**Issue by su-Koch** [espressif/idf-extra-components#189]
### Answers checklist.

- [X] I have read the documentation of the component in question and the issue is not addressed there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello,
can you provide some examples for the use of this library.
E.g.: How can I use it to run ds18b20?
Regards Manuel

**Comment by suda-morris** [comment]
@su-Koch I guess you have already found the place: https://github.com/espressif/esp-idf/tree/master/examples/peripherals/rmt/onewire

link in your another github issue in the esp-idf: https://github.com/espressif/esp-idf/issues/11666
