### ISSUE TITLE
tinyusb_msc_storage_mount make max files as a configurable option (IEC-33)

### ISSUE THREAD

**Issue by haipas** [espressif/idf-extra-components#217]
### Is your feature request related to a problem?

Hello,
currently, the maximum opened files is set to 2. We need this configurable up to 5 files.

` FATFS *fs = NULL;
    ret = esp_vfs_fat_register(base_path, drv, 2, &fs);
    if (ret == ESP_ERR_INVALID_STATE) {
        ESP_LOGD(TAG, "it's okay, already registered with VFS");
    } else if (ret != ESP_OK) {
        ESP_LOGE(TAG, "esp_vfs_fat_register failed (0x%x)", ret);
        goto fail;
    }
`

### Describe the solution you'd like.

Make the number of maximum opened files as a config option inside the sdkonfig.

**Comment by tore-espressif** [comment]
@haipas Thank you for the report. We must have missed this during review of the initial version. Will be fixed
