### ISSUE TITLE
CMake Error at /home/ai/esp/esp-idf/tools/cmake/build.cmake:519 (message):   ERROR: Solver failed processing dependency "espressif/usb_host_cdc_acm"   from the manifest file "/***/idf_component.yml". (IEC-39)

### ISSUE THREAD

**Issue by 287662354** [espressif/idf-extra-components#226]
### Answers checklist.

- [X] I have read the component documentation [ESP-IDF Components](https://components.espressif.com) and the issue is not addressed there.
- [X] I am using target and esp-idf version as defined in component's idf_component.yml
- [X] I have searched the [issue tracker](https://github.com/espressif/idf-extra-components/issues?q=is%3Aissue) for a similar issue and not found any related issue.

### Which component are you using? If you choose Other, provide details in More Information.

bdc_motor

### ESP-IDF version.

espidf5.0.2

### Development Kit.

custome board

### Used Component version.

2.0.0

### More Information.

打算从meshlite 0.2改成0.4  删除yml文件后重新添加依赖meshlite    mordem等,结果 移植报错HTTP request error报错  无法拉取esp_modem_usb_dte,
修改后的yml文件如下:
dependencies:
  joltwallet/littlefs: "^1.7.0"
  espressif/mesh_lite: "^0.4.0"
  espressif/esp_modem:
    version: 0.*
  espressif/esp_modem_usb_dte:
    public: true
    rules:
    - if: target in [esp32s2, esp32s3]
    - if: idf_version >= 4.4
    version: 1.*
  ## Required IDF version
  idf:
    version: ">=4.1.0"

**Comment by leeebo** [comment]
如果更新 component manager 再测试一下

```
pip install idf_component_manager --upgrade
```
