### ISSUE TITLE
Setting Brightness (IEC-63)

### ISSUE THREAD

**Issue by ncpe20012003** [espressif/idf-extra-components#256]
### Answers checklist.

- [X] I have read the documentation of the component in question and the issue is not addressed there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

How to set the brightness for ws2812?

**Comment by suda-morris** [comment]
You can do it by scaling the RGB values of each LED by multiplying them by a factor between 0 and 1.
