### ISSUE TITLE
libsodium 1.0.19 (IEC-64)

### ISSUE THREAD

**Issue by skibz** [espressif/idf-extra-components#257]
### Answers checklist.

- [X] I have read the documentation of the component in question and the issue is not addressed there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Good day

I'm sorry if this is the wrong place to post this...

I wanted to find out if there are plans to sync up the libsodium component with the latest upstream changes from jedisct1/libsodium?

The most up to date version is [1.0.19](https://github.com/jedisct1/libsodium/releases/tag/1.0.19-RELEASE) and was released in mid-September.

What is the usual workflow for getting the latest code from upstream? And is it something that I could possibly assist with?

Kind regards

**Comment by mahavirj** [comment]
@skibz Create PR for this at https://github.com/espressif/idf-extra-components/pull/262
