### ISSUE TITLE
libsodium component is missing sources from CMakeLists (IEC-239)

### ISSUE THREAD

**Issue by bm-l** [espressif/idf-extra-components#449]
### Answers checklist.

- [X] I have read the documentation of the component in question and the issue is not addressed there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

A handful of upstream source files are missing from the CMakeLists.txt provided for libsodium.

Among them:

- aead_aegis256.c
- aegis256_soft.c
- aead_aegis128l.c
- aegis128l_soft.c
- softaes.c

This results in build failures with "undefined reference to..." when using the libsodium component.

**Comment by mahavirj** [comment]
@bm-l  Please try your build with https://github.com/espressif/idf-extra-components/pull/450

**Comment by bm-l** [comment]
Build was successful, thankyou 😃
